# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_excel('Data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 7654 samples
Epoch 1/100
7654/7654 [==============================] - 1s 88us/sample - loss: 204993.0156
Epoch 2/100
7654/7654 [==============================] - 0s 25us/sample - loss: 192091.7942
Epoch 3/100
7654/7654 [==============================] - 0s 25us/sample - loss: 154563.3656
Epoch 4/100
7654/7654 [==============================] - 0s 25us/sample - loss: 103763.5017
Epoch 5/100
7654/7654 [==============================] - 0s 25us/sample - loss: 62484.6412
Epoch 6/100
7654/7654 [==============================] - 0s 25us/sample - loss: 35346.6498
Epoch 7/100
7654/7654 [==============================] - 0s 25us/sample - loss: 19355.8080
Epoch 8/100
7654/7654 [==============================] - 0s 25us/sample - loss: 11673.7898
Epoch 9/100
7654/7654 [==============================] - 0s 26us/sample - loss: 7992.0834
Epoch 10/100
7654/7654 [==============================] - 0s 25us/sample - loss: 5680.9795
Epoch 11/100
7654/7654 [==============================] - 0s 25us

### Predicting the results of the Test set

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.3  431.23]
 [458.58 460.01]
 [462.8  461.14]
 ...
 [469.55 473.26]
 [441.93 438.  ]
 [461.48 463.28]]


# Calculate the R2_Score

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9357243689762723

# Saving the  scaler


In [18]:
import joblib
joblib.dump(sc, 'scaler', compress=True)

['scaler']

In [23]:
scaler = joblib.load('scaler')

# Saving the model

In [19]:
ann.save('regressor.h5')

In [20]:
model = tf.keras.models.load_model('regressor.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  30        
_________________________________________________________________
dense_1 (Dense)              multiple                  42        
_________________________________________________________________
dense_2 (Dense)              multiple                  7         
Total params: 79
Trainable params: 79
Non-trainable params: 0
_________________________________________________________________


In [21]:
ann.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  30        
_________________________________________________________________
dense_1 (Dense)              multiple                  42        
_________________________________________________________________
dense_2 (Dense)              multiple                  7         
Total params: 79
Trainable params: 79
Non-trainable params: 0
_________________________________________________________________


# predict an energy using same model and loaded model

In [22]:
ann.predict(sc.transform([[25.18, 62.96, 1020.04, 59.08]]))

array([[443.98]], dtype=float32)

In [25]:
x = model.predict(scaler.transform([[25.18, 62.96, 1020.04, 59.08]]))

In [27]:
type(x)

numpy.ndarray

In [28]:
x.shape

(1, 1)

In [29]:
x


array([[443.98]], dtype=float32)

In [33]:
float(x[0][0])

443.9823913574219